// <auto-generated />
using System;
using Lotus.Account;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lotus.Account.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20251221132040_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lotus.Account.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("HashId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Interests")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsLockout")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutBeginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Whereabouts")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "adm");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3182c8f-87bc-4e27-a27f-b32e3e2b8018"),
                            Birthday = new DateOnly(1984, 9, 19),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dementevds@gmail.com",
                            EmailConfirmed = false,
                            HashId = "de37c95205934914eed14aaab97c1b4c53d31566",
                            IsLockout = false,
                            Login = "DanielDem",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Даниил",
                            PasswordHash = "012f28fd2973783520fa3115f886102a09c8a15e",
                            Patronymic = "Сергеевич",
                            RoleId = 1,
                            Surname = "Дементьев"
                        },
                        new
                        {
                            Id = new Guid("a2183c9f-98ac-5b38-b28f-c43e3e3c9029"),
                            Birthday = new DateOnly(1990, 5, 15),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.ivanova@example.com",
                            EmailConfirmed = false,
                            HashId = "c6fb5e2653f796e04a2ed6f7d768f56f321c6113",
                            IsLockout = false,
                            Login = "SeniorEditor",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Мария",
                            PasswordHash = "32c404655d2e85a15edca3d2e3fbc5a46548b366",
                            Patronymic = "Петровна",
                            PostId = 2,
                            RoleId = 2,
                            Surname = "Иванова"
                        },
                        new
                        {
                            Id = new Guid("b3194d0a-09bd-6c49-c39a-d54f4f4da13a"),
                            Birthday = new DateOnly(1988, 7, 22),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.smirnov@example.com",
                            EmailConfirmed = false,
                            HashId = "a30ba3133f994b8e1ca4abf2932619990af3eebf",
                            IsLockout = false,
                            Login = "ContentManager",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Алексей",
                            PasswordHash = "45e6b7fc636bea009563b827cc5bbe3dcf736866",
                            Patronymic = "Александрович",
                            PostId = 2,
                            RoleId = 2,
                            Surname = "Смирнов"
                        },
                        new
                        {
                            Id = new Guid("c41a5e1b-1ace-7d5a-d4ab-e6505f5eb24b"),
                            Birthday = new DateOnly(1992, 3, 10),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "olga.petrova@example.com",
                            EmailConfirmed = false,
                            HashId = "80ce6f5080b2d8495cca23a0f08fd72b4245525a",
                            IsLockout = false,
                            Login = "Moderator",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ольга",
                            PasswordHash = "e7b96f3e8611f382aacf582b5e1f3093e16e5396",
                            Patronymic = "Сергеевна",
                            PostId = 3,
                            RoleId = 2,
                            Surname = "Петрова"
                        },
                        new
                        {
                            Id = new Guid("d52b6f2c-2bdf-8e6b-e5bc-f7616f6fc35c"),
                            Birthday = new DateOnly(1995, 11, 30),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sergey.kuznetsov@example.com",
                            EmailConfirmed = false,
                            HashId = "b91bd41bdd32e3697f8b038011b228c1676540ed",
                            IsLockout = false,
                            Login = "AssistantEditor",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Сергей",
                            PasswordHash = "e97e7fab6e759c9b07f244c9992f326ed8d54b21",
                            Patronymic = "Игоревич",
                            PostId = 1,
                            RoleId = 2,
                            Surname = "Кузнецов"
                        },
                        new
                        {
                            Id = new Guid("e63c702d-3cf0-9f7c-f6cd-08727070d46d"),
                            Birthday = new DateOnly(1991, 8, 5),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.vorobeva@example.com",
                            EmailConfirmed = false,
                            HashId = "5ca09651599ee9faaca9deff228b00a34fd7e75a",
                            IsLockout = false,
                            Login = "NewsEditor",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Елена",
                            PasswordHash = "fa0ec050421ef5ba51fe018a5353bd4a8955836f",
                            Patronymic = "Андреевна",
                            PostId = 1,
                            RoleId = 2,
                            Surname = "Воробьева"
                        },
                        new
                        {
                            Id = new Guid("f74d813e-4d01-a08d-07de-19838181e57e"),
                            Birthday = new DateOnly(1987, 4, 18),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr.specialist@example.com",
                            EmailConfirmed = false,
                            HashId = "896d92b3f39d0935ba3c34bef404e075a4ff4e29",
                            IsLockout = false,
                            Login = "HrSpecialist",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Анна",
                            PasswordHash = "ba7a813321daaa2e5e876e868c980ba01cb17c5e",
                            Patronymic = "Владимировна",
                            PostId = 1,
                            RoleId = 3,
                            Surname = "Соколова"
                        },
                        new
                        {
                            Id = new Guid("085e924f-5e12-b19e-18ef-2a949292f68f"),
                            Birthday = new DateOnly(1983, 12, 25),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "group.manager@example.com",
                            EmailConfirmed = false,
                            HashId = "6aae61b6e03db134b1247b7671d7673350836a32",
                            IsLockout = false,
                            Login = "DepartmentManager",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Дмитрий",
                            PasswordHash = "5a85bbe33e342ac9b1a2ad2abb6125c3a100b197",
                            Patronymic = "Николаевич",
                            PostId = 4,
                            RoleId = 4,
                            Surname = "Попов"
                        },
                        new
                        {
                            Id = new Guid("196f7248-1a23-4c45-b567-890123456789"),
                            Birthday = new DateOnly(1993, 2, 14),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ivan.sidorov@example.com",
                            EmailConfirmed = false,
                            HashId = "f782668d2499e6a4352906a23934082f2931ddcb",
                            IsLockout = false,
                            Login = "UserIvanSidorov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Иван",
                            PasswordHash = "0fc688ae3631ec2dde193be859af930dcfe99e32",
                            Patronymic = "Михайлович",
                            RoleId = 100,
                            Surname = "Сидоров"
                        },
                        new
                        {
                            Id = new Guid("287a8359-2b34-5d56-c678-901234567890"),
                            Birthday = new DateOnly(1994, 6, 8),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ekaterina.kuzmina@example.com",
                            EmailConfirmed = false,
                            HashId = "cf93873eaf0fc9406ae5c5eace239003e91260c4",
                            IsLockout = false,
                            Login = "UserEkaterinaKuzmina",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Екатерина",
                            PasswordHash = "6edcb8a7c16928ad141fa67d307fe55d6bc1df03",
                            Patronymic = "Александровна",
                            RoleId = 100,
                            Surname = "Кузьмина"
                        },
                        new
                        {
                            Id = new Guid("398b946a-3c45-6e67-d789-012345678901"),
                            Birthday = new DateOnly(1996, 9, 21),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "petr.volkov@example.com",
                            EmailConfirmed = false,
                            HashId = "e243cb7da6970df8c7e435a77178b20473e13c0e",
                            IsLockout = false,
                            Login = "UserPetrVolkov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Петр",
                            PasswordHash = "0c43b441690a3e8864b80f1ffa2df97785a4a3c7",
                            Patronymic = "Сергеевич",
                            RoleId = 100,
                            Surname = "Волков"
                        },
                        new
                        {
                            Id = new Guid("4a9c057b-4d56-7f78-e89a-123456789012"),
                            Birthday = new DateOnly(1990, 11, 3),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "natalia.fedorova@example.com",
                            EmailConfirmed = false,
                            HashId = "f005398f4c86b4f0a102733be85a700dca8cbbcd",
                            IsLockout = false,
                            Login = "UserNataliaFedorova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Наталия",
                            PasswordHash = "daee69ffeb9f6caf8f909ad6deaaa0c9b7d05533",
                            Patronymic = "Ивановна",
                            RoleId = 100,
                            Surname = "Федорова"
                        },
                        new
                        {
                            Id = new Guid("5bad168c-5e67-8089-f9ab-234567890123"),
                            Birthday = new DateOnly(1989, 1, 17),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "andrey.morozov@example.com",
                            EmailConfirmed = false,
                            HashId = "6c78aeb8bfc4526b1fc7a8b19b1aecfdadb22072",
                            IsLockout = false,
                            Login = "UserAndreyMorozov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Андрей",
                            PasswordHash = "7db05ccba601bebeba0a44cdfa822c2cf90c8b91",
                            Patronymic = "Петрович",
                            RoleId = 100,
                            Surname = "Морозов"
                        },
                        new
                        {
                            Id = new Guid("6cbe279d-6f78-919a-0abc-345678901234"),
                            Birthday = new DateOnly(1992, 4, 29),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tatiana.orlova@example.com",
                            EmailConfirmed = false,
                            HashId = "c7440857ba3e5d406e53720d0701dbc4a66e4afd",
                            IsLockout = false,
                            Login = "UserTatianaOrlova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Татьяна",
                            PasswordHash = "98325980136d016b62bc5901b58d21bef2873a32",
                            Patronymic = "Владимировна",
                            RoleId = 100,
                            Surname = "Орлова"
                        },
                        new
                        {
                            Id = new Guid("7dcf38ae-7089-a2ab-1bcd-456789012345"),
                            Birthday = new DateOnly(1995, 7, 12),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mikhail.belov@example.com",
                            EmailConfirmed = false,
                            HashId = "000aa1ddf3ebb90bee3ff03be62392ced406d862",
                            IsLockout = false,
                            Login = "UserMikhailBelov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Михаил",
                            PasswordHash = "64ef46a98948a6b3004344a92439268f2821439c",
                            Patronymic = "Андреевич",
                            RoleId = 100,
                            Surname = "Белов"
                        },
                        new
                        {
                            Id = new Guid("8ed049bf-819a-b3bc-2cde-567890123456"),
                            Birthday = new DateOnly(1991, 10, 5),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "svetlana.komarova@example.com",
                            EmailConfirmed = false,
                            HashId = "2afe5cf28a7dbd28a804df2c97a95f78916d24fa",
                            IsLockout = false,
                            Login = "UserSvetlanaKomarova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Светлана",
                            PasswordHash = "75846a576cd353c9c40189d1e0e0fd196c474cc8",
                            Patronymic = "Николаевна",
                            RoleId = 100,
                            Surname = "Комарова"
                        },
                        new
                        {
                            Id = new Guid("9fe15ac0-92ab-c4cd-3def-678901234567"),
                            Birthday = new DateOnly(1988, 3, 8),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vladimir.egorov@example.com",
                            EmailConfirmed = false,
                            HashId = "d907219b136d64dbde99cd146ab3640c20609e17",
                            IsLockout = false,
                            Login = "UserVladimirEgorov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Владимир",
                            PasswordHash = "6befe3e5862aaf5ad4d01a92506fb2ab3fc17500",
                            Patronymic = "Викторович",
                            RoleId = 100,
                            Surname = "Егоров"
                        },
                        new
                        {
                            Id = new Guid("0af26bd1-a3bc-d5de-4ef0-789012345678"),
                            Birthday = new DateOnly(1997, 12, 15),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "julia.zhukova@example.com",
                            EmailConfirmed = false,
                            HashId = "702a94f8f611881336b4029594dab9183ed6f7e5",
                            IsLockout = false,
                            Login = "UserJuliaZhukova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Юлия",
                            PasswordHash = "f898451c1aa7f8588c50cefd2bacb210b3e03d38",
                            Patronymic = "Алексеевна",
                            RoleId = 100,
                            Surname = "Жукова"
                        },
                        new
                        {
                            Id = new Guid("1b037ce2-b4cd-e6ef-5f01-890123456789"),
                            Birthday = new DateOnly(1994, 5, 22),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "roman.kirillov@example.com",
                            EmailConfirmed = false,
                            HashId = "e00751932586751e36d9bc7c94e1c1c4a1f287ce",
                            IsLockout = false,
                            Login = "UserRomanKirillov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Роман",
                            PasswordHash = "e59cdd89c7d2db6c6a15f811d329f8c0428f7995",
                            Patronymic = "Олегович",
                            RoleId = 100,
                            Surname = "Кириллов"
                        },
                        new
                        {
                            Id = new Guid("2c148df3-c5de-f7f0-6012-901234567890"),
                            Birthday = new DateOnly(1993, 8, 14),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alena.semenova@example.com",
                            EmailConfirmed = false,
                            HashId = "15c0ecc67e8435db7c684f7ed4e18f796fab41c1",
                            IsLockout = false,
                            Login = "UserAlenaSemenova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Алена",
                            PasswordHash = "487cc7ba340b0239e9bdbbdd0ba3c34573c8d6cc",
                            Patronymic = "Дмитриевна",
                            RoleId = 100,
                            Surname = "Семенова"
                        },
                        new
                        {
                            Id = new Guid("3d259ef4-d6ef-08f1-7123-012345678901"),
                            Birthday = new DateOnly(1990, 1, 27),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "artem.gusev@example.com",
                            EmailConfirmed = false,
                            HashId = "d557060eb2e72c6ed0c9861535203af315ac81fe",
                            IsLockout = false,
                            Login = "UserArtemGusev",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Артем",
                            PasswordHash = "5c2368889e676fed0a01f9ccef9765b79e9488ab",
                            Patronymic = "Васильевич",
                            RoleId = 100,
                            Surname = "Гусев"
                        },
                        new
                        {
                            Id = new Guid("4e36af05-e7f0-19f2-8234-123456789012"),
                            Birthday = new DateOnly(1987, 11, 9),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "larisa.titova@example.com",
                            EmailConfirmed = false,
                            HashId = "a8400621ea9941bbf323f4742892b0f899da4d82",
                            IsLockout = false,
                            Login = "UserLarisaTitova",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Лариса",
                            PasswordHash = "0c432e7051a5390da240440859dc78f5fb6cb909",
                            Patronymic = "Юрьевна",
                            RoleId = 100,
                            Surname = "Титова"
                        },
                        new
                        {
                            Id = new Guid("5f47b006-f8f1-2af3-9345-234567890123"),
                            Birthday = new DateOnly(1996, 6, 3),
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pavel.rybakov@example.com",
                            EmailConfirmed = false,
                            HashId = "149fd9f9da683e19e4ace04a7bd18af5c182d2c1",
                            IsLockout = false,
                            Login = "UserPavelRybakov",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Павел",
                            PasswordHash = "858455381aafb12a1a9f3b5bea077296afcc2877",
                            Patronymic = "Геннадьевич",
                            RoleId = 100,
                            Surname = "Рыбаков"
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserFieldActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserFieldActivity", "adm");
                });

            modelBuilder.Entity("Lotus.Account.UserFieldActivityRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldActivityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FieldActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFieldActivityRelation", "adm");
                });

            modelBuilder.Entity("Lotus.Account.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserGroup", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Хранители",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Хранители"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Север",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Север"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Юг",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Юг"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Восток",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Восток"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Запад",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Запад"
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserGroupRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupRelation", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            UserId = new Guid("e3182c8f-87bc-4e27-a27f-b32e3e2b8018")
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            UserId = new Guid("a2183c9f-98ac-5b38-b28f-c43e3e3c9029")
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 1,
                            UserId = new Guid("b3194d0a-09bd-6c49-c39a-d54f4f4da13a")
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 1,
                            UserId = new Guid("085e924f-5e12-b19e-18ef-2a949292f68f")
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 2,
                            UserId = new Guid("c41a5e1b-1ace-7d5a-d4ab-e6505f5eb24b")
                        },
                        new
                        {
                            Id = 6,
                            GroupId = 2,
                            UserId = new Guid("d52b6f2c-2bdf-8e6b-e5bc-f7616f6fc35c")
                        },
                        new
                        {
                            Id = 7,
                            GroupId = 2,
                            UserId = new Guid("e63c702d-3cf0-9f7c-f6cd-08727070d46d")
                        },
                        new
                        {
                            Id = 8,
                            GroupId = 2,
                            UserId = new Guid("f74d813e-4d01-a08d-07de-19838181e57e")
                        },
                        new
                        {
                            Id = 9,
                            GroupId = 4,
                            UserId = new Guid("196f7248-1a23-4c45-b567-890123456789")
                        },
                        new
                        {
                            Id = 10,
                            GroupId = 4,
                            UserId = new Guid("287a8359-2b34-5d56-c678-901234567890")
                        },
                        new
                        {
                            Id = 11,
                            GroupId = 4,
                            UserId = new Guid("398b946a-3c45-6e67-d789-012345678901")
                        },
                        new
                        {
                            Id = 12,
                            GroupId = 4,
                            UserId = new Guid("4a9c057b-4d56-7f78-e89a-123456789012")
                        },
                        new
                        {
                            Id = 13,
                            GroupId = 3,
                            UserId = new Guid("5bad168c-5e67-8089-f9ab-234567890123")
                        },
                        new
                        {
                            Id = 14,
                            GroupId = 3,
                            UserId = new Guid("6cbe279d-6f78-919a-0abc-345678901234")
                        },
                        new
                        {
                            Id = 15,
                            GroupId = 3,
                            UserId = new Guid("7dcf38ae-7089-a2ab-1bcd-456789012345")
                        },
                        new
                        {
                            Id = 16,
                            GroupId = 3,
                            UserId = new Guid("8ed049bf-819a-b3bc-2cde-567890123456")
                        },
                        new
                        {
                            Id = 17,
                            GroupId = 5,
                            UserId = new Guid("9fe15ac0-92ab-c4cd-3def-678901234567")
                        },
                        new
                        {
                            Id = 18,
                            GroupId = 5,
                            UserId = new Guid("0af26bd1-a3bc-d5de-4ef0-789012345678")
                        },
                        new
                        {
                            Id = 19,
                            GroupId = 5,
                            UserId = new Guid("1b037ce2-b4cd-e6ef-5f01-890123456789")
                        },
                        new
                        {
                            Id = 20,
                            GroupId = 5,
                            UserId = new Guid("2c148df3-c5de-f7f0-6012-901234567890")
                        },
                        new
                        {
                            Id = 21,
                            GroupId = 4,
                            UserId = new Guid("3d259ef4-d6ef-08f1-7123-012345678901")
                        },
                        new
                        {
                            Id = 22,
                            GroupId = 3,
                            UserId = new Guid("4e36af05-e7f0-19f2-8234-123456789012")
                        },
                        new
                        {
                            Id = 23,
                            GroupId = 5,
                            UserId = new Guid("5f47b006-f8f1-2af3-9345-234567890123")
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("UserMessage", "adm");
                });

            modelBuilder.Entity("Lotus.Account.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserNotification", "adm");
                });

            modelBuilder.Entity("Lotus.Account.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserPermission", "adm");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр пользователей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UserView"
                        },
                        new
                        {
                            Id = 102,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление пользователей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UserAdd"
                        },
                        new
                        {
                            Id = 103,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование пользователей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UserEdit"
                        },
                        new
                        {
                            Id = 104,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление пользователей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "UserRemove"
                        },
                        new
                        {
                            Id = 201,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр ролей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "RoleView"
                        },
                        new
                        {
                            Id = 202,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление ролей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "RoleAdd"
                        },
                        new
                        {
                            Id = 203,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование ролей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "RoleEdit"
                        },
                        new
                        {
                            Id = 204,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление ролей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "RoleRemove"
                        },
                        new
                        {
                            Id = 301,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр разрешений",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PermissionView"
                        },
                        new
                        {
                            Id = 302,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление разрешений",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PermissionAdd"
                        },
                        new
                        {
                            Id = 303,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование разрешений",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PermissionEdit"
                        },
                        new
                        {
                            Id = 304,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление разрешений",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PermissionRemove"
                        },
                        new
                        {
                            Id = 401,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PositionView"
                        },
                        new
                        {
                            Id = 402,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PositionAdd"
                        },
                        new
                        {
                            Id = 403,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PositionEdit"
                        },
                        new
                        {
                            Id = 404,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PositionRemove"
                        },
                        new
                        {
                            Id = 405,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Выбор должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PositionChoose"
                        },
                        new
                        {
                            Id = 501,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GroupView"
                        },
                        new
                        {
                            Id = 502,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GroupAdd"
                        },
                        new
                        {
                            Id = 503,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GroupEdit"
                        },
                        new
                        {
                            Id = 504,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GroupRemove"
                        },
                        new
                        {
                            Id = 505,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Выбор групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "GroupChoose"
                        },
                        new
                        {
                            Id = 601,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Просмотр направлений деятельности",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FieldActivityView"
                        },
                        new
                        {
                            Id = 602,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Добавление направлений деятельности",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FieldActivityAdd"
                        },
                        new
                        {
                            Id = 603,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактирование направлений деятельности",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FieldActivityEdit"
                        },
                        new
                        {
                            Id = 604,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Удаление направлений деятельности",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FieldActivityRemove"
                        },
                        new
                        {
                            Id = 605,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Выбор направлений деятельности",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "FieldActivityChoose"
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserPosition", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Инспектор",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Инспектор"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Старший инспектор",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Старший инспектор"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Ведущий специалист",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ведущий специалист"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Начальник отдела",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Начальник отдела"
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserRole", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Администратор",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактор",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "editor"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактор должностей",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "editorPost"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Редактор групп",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "editorGroup"
                        },
                        new
                        {
                            Id = 100,
                            Created = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Пользователь",
                            Modified = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Lotus.Account.UserRolePermissionRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRolePermissionRelation", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 101,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 102,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 103,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 104,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 201,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 202,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 203,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 204,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 301,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 302,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 303,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 304,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 401,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 402,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 403,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 404,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 405,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 501,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 502,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 503,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 504,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 505,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 601,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 602,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 603,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 604,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 605,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 201,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 301,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 401,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 405,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 501,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 505,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 601,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 605,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 401,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            PermissionId = 402,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 38,
                            PermissionId = 403,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 39,
                            PermissionId = 404,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            PermissionId = 405,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 41,
                            PermissionId = 201,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            PermissionId = 301,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            PermissionId = 501,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            PermissionId = 505,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 45,
                            PermissionId = 601,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 46,
                            PermissionId = 605,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            PermissionId = 501,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 48,
                            PermissionId = 502,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 49,
                            PermissionId = 503,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            PermissionId = 504,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            PermissionId = 505,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            PermissionId = 201,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 53,
                            PermissionId = 301,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 54,
                            PermissionId = 401,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 55,
                            PermissionId = 405,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 56,
                            PermissionId = 601,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            PermissionId = 605,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 58,
                            PermissionId = 101,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 59,
                            PermissionId = 201,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 60,
                            PermissionId = 301,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 61,
                            PermissionId = 401,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 62,
                            PermissionId = 501,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 63,
                            PermissionId = 601,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 64,
                            PermissionId = 405,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 65,
                            PermissionId = 505,
                            RoleId = 100
                        },
                        new
                        {
                            Id = 66,
                            PermissionId = 605,
                            RoleId = 100
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", "security");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", "security");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", "security");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", "security");
                });

            modelBuilder.Entity("Lotus.Account.User", b =>
                {
                    b.HasOne("Lotus.Account.UserPosition", "Post")
                        .WithMany("Users")
                        .HasForeignKey("PostId");

                    b.HasOne("Lotus.Account.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lotus.Account.UserFieldActivityRelation", b =>
                {
                    b.HasOne("Lotus.Account.UserFieldActivity", null)
                        .WithMany()
                        .HasForeignKey("FieldActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lotus.Account.UserGroupRelation", b =>
                {
                    b.HasOne("Lotus.Account.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lotus.Account.UserMessage", b =>
                {
                    b.HasOne("Lotus.Account.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Lotus.Account.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.Navigation("Author");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Lotus.Account.UserRolePermissionRelation", b =>
                {
                    b.HasOne("Lotus.Account.UserPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Lotus.Account.UserPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lotus.Account.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
