export const LocalizationAccountDataEn = {
  auth: {
    account: 'Account',
    entrance: 'Login',
    password: 'Password',
    remember: 'Remember me',
    term: 'I accept terms and conditions',
    comeIn: 'Log in',
    autoComeIn: 'Auto-login',
    forgotPassword: 'Forgot password',
    register: 'Sign up',
    authFailed: 'Authentication error',
    registration: 'Registration',
    registrationFailed: 'Registration error',
    restorePassword: 'Enter email to reset password',
    send: 'Send',
    logout: 'Log out',
    accessDenied: 'Access denied'
  },
  group: {
    groups: 'Groups',
    id: 'ID',
    idDesc: 'Group identifier',
    name: 'Name',
    nameDesc: 'Full group name',
    displayName: 'Display name',
    displayNameDesc: 'Group display name',
    edit: 'Edit',
    editDesc: 'Edit group',
    save: 'Save',
    saveDesc: 'Save group',
    duplicate: 'Duplicate',
    duplicateDesc: 'Duplicate group',
    delete: 'Delete',
    deleteDesc: 'Delete group',
    cancel: 'Cancel',
    cancelDesc: 'Cancel group changes'
  },
  notification: {
    id: 'ID',
    idDesc: 'Notification identifier',
    topic: 'Subject',
    topicDesc: 'Notification subject',
    sender: 'Source',
    senderDesc: 'Notification source',
    importance: 'Priority',
    importanceDesc: 'Notification priority',
    content: 'Content',
    contentDesc: 'Notification content',
    created: 'Date',
    createdDesc: 'Notification date',
    notification: 'Notifications',
    importanceChief: 'High',
    importanceNormal: 'Normal',
    importanceService: 'Service',
    read: 'Mark as read',
    readCancel: 'Mark as unread',
    toArchive: 'Archive',
    fromArchive: 'Unarchive'
  },
  permission: {
    permissions: 'Permissions',
    id: 'ID',
    idDesc: 'Permission identifier',
    name: 'Name',
    nameDesc: 'Internal permission name',
    displayName: 'Display name',
    displayNameDesc: 'Permission display name'
  },
  position: {
    positions: 'Positions',
    id: 'ID',
    idDesc: 'Position identifier',
    name: 'Name',
    nameDesc: 'Full position name',
    displayName: 'Display name',
    displayNameDesc: 'Position display name',
    edit: 'Edit',
    editDesc: 'Edit position',
    save: 'Save',
    saveDesc: 'Save position',
    duplicate: 'Duplicate',
    duplicateDesc: 'Duplicate position',
    delete: 'Delete',
    deleteDesc: 'Delete position',
    cancel: 'Cancel',
    cancelDesc: 'Cancel position changes'
  },
  profile: {
    profile: 'Profile'
  },
  role: {
    roles: 'Roles',
    id: 'ID',
    idDesc: 'Role identifier',
    name: 'Name',
    nameDesc: 'Internal role name',
    displayName: 'Display name',
    displayNameDesc: 'Role display name',
    permissionIds: 'Permissions',
    permissionIdsDesc: 'List of permissions for this role'
  },
  settings: {
    settings: 'Settings',
    theme: 'Theme',
    themeLight: 'Light theme',
    themeDark: 'Dark theme',
    viewParams: 'Display settings',
    showHeader: 'Show header',
    showFooter: 'Show footer'
  },
  user: {
    users: 'Users',
    fio: 'Full name',
    name: 'First name',
    surname: 'Last name',
    fathersName: 'Middle name',
    birthday: 'Date of birth',
    snils: 'SNILS number',
    phoneNumber: 'Phone number',
    roleName: 'Role',
    profileNames: 'Profiles',
    organizationName: 'Organization'
  },
  account:
  {
    profile: 'Личные данные',
    settings: 'Настройки',
    security: 'Безопасность'
  }
};
