export const LocalizationAccountDataRu =
{
  auth: {
    account: 'Аккаунт',
    entrance: 'Вход',
    continueWith: 'Или вход по логину/почте и паролю',
    password: 'Пароль',
    remember: 'Запомнить меня',
    term: 'Я принимаю пользовательское соглашение',
    comeIn: 'Войти',
    autoComeIn: 'Автоматический вход на сайт',
    forgotPassword: 'Забыли пароль',
    register: 'Зарегистрироваться',
    authFailed: 'При авторизации произошла ошибка',
    registration: 'Регистрация',
    registrationFailed: 'При регистрации произошла ошибка',
    restorePassword: 'Укажите почту для восстановления пароля',
    send: 'Отправить',
    logout: 'Выйти',
    login: 'Логин/email',
    accessDenied: 'Доступ к ресурсу запрещён',
    placeholderLogin: 'Введите логин/email',
    placeholderPassword: 'Введите пароль',
    infoLastLogin: 'Не аутентифицирован. Последний вход: {formattedDate} ({timeAgo} назад)',
    infoSavedSession: 'Сессия сохранена. Для входа используйте автоматический вход или введите учетные данные',
    infoNotAuth: 'Не аутентифицирован. Для доступа к защищенным ресурсам выполните вход',
  },
  token: {
    // Сообщения о просроченности токена
    expiredShort: 'Токен истек',
    expiredMedium: 'Токен истек. Требуется обновление',
    expiredFull: 'Срок действия токена истек. Необходимо повторно войти в систему',

    // Форматированные сообщения при действующем токене
    validShort: 'Действителен до: {date}',
    validMedium: 'Истекает: {date} ({duration})',
    validFull: 'Токен действителен до {date}. Осталось: {duration}. Истечет {relative}.',
  },
  group: {
    groups: 'Группы',
    id: 'ИД',
    idDesc: 'Идентификатор группы',
    name: 'Наименование',
    nameDesc: 'Полное наименование группы',
    displayName: 'Отображаемое наименование',
    displayNameDesc: 'Отображаемое наименование группы',
    edit: 'Редактировать',
    editDesc: 'Редактировать группу',
    save: 'Сохранить',
    saveDesc: 'Сохранить группу',
    duplicate: 'Дублировать',
    duplicateDesc: 'Дублировать группу',
    delete: 'Удалить',
    deleteDesc: 'Удалить группу',
    cancel: 'Отменить',
    cancelDesc: 'Отменить изменения группы'
  },
  notification: {
    id: 'ИД',
    idDesc: 'Идентификатор уведомления',
    topic: 'Тема',
    topicDesc: 'Тема уведомления',
    sender: 'Источник',
    senderDesc: 'Источник уведомления',
    importance: 'Важность',
    importanceDesc: 'Важность уведомления',
    content: 'Содержимое',
    contentDesc: 'Содержимое уведомления',
    created: 'Дата',
    createdDesc: 'Дата уведомления',
    notification: 'Уведомления',
    importanceChief: 'Важное',
    importanceNormal: 'Обычное',
    importanceService: 'Служебное',
    read: 'Прочитать',
    readCancel: 'Отменить прочитано',
    toArchive: 'В архив',
    fromArchive: 'Из архива'
  },
  permission: {
    permissions: 'Разрешения',
    id: 'ИД',
    idDesc: 'Идентификатор разрешения',
    name: 'Наименование',
    nameDesc: 'Служебное наименование разрешения',
    displayName: 'Наименование',
    displayNameDesc: 'Наименование разрешения'
  },
  position: {
    positions: 'Должности',
    id: 'ИД',
    idDesc: 'Идентификатор должности',
    name: 'Наименование',
    nameDesc: 'Полное наименование должности',
    displayName: 'Отображаемое наименование',
    displayNameDesc: 'Отображаемое наименование должности',
    edit: 'Редактировать',
    editDesc: 'Редактировать должность',
    save: 'Сохранить',
    saveDesc: 'Сохранить должность',
    duplicate: 'Дублировать',
    duplicateDesc: 'Дублировать должность',
    delete: 'Удалить',
    deleteDesc: 'Удалить должность',
    cancel: 'Отменить',
    cancelDesc: 'Отменить изменения должности'
  },
  profile: {
    profile: 'Профиль'
  },
  role: {
    roles: 'Роли',
    id: 'ИД',
    idDesc: 'Идентификатор роли',
    name: 'Наименование',
    nameDesc: 'Служебное наименование роли',
    displayName: 'Наименование',
    displayNameDesc: 'Наименование роли',
    permissionIds: 'Разрешения',
    permissionIdsDesc: 'Список разрешений для данной роли'
  },
  settings: {
    settings: 'Настройки',
    theme: 'Тема',
    themeLight: 'Светлая тема',
    themeDark: 'Темная тема',
    viewParams: 'Параметры отображения',
    showHeader: 'Показать заголовок',
    showFooter: 'Показать подвал'
  },
  user: {
    users: 'Пользователи',
    fio: 'ФИО',
    name: 'Имя',
    surname: 'Фамилия',
    fathersName: 'Отчество',
    birthday: 'Дата рождения',
    snils: 'Номер СНИЛС',
    phoneNumber: 'Номер телефона',
    roleName: 'Роль',
    profileNames: 'Профили',
    organizationName: 'Организация',
  },
  account:
  {
    profile: 'Личные данные',
    settings: 'Настройки',
    security: 'Безопасность'
  }
};
