export const LocalizationAccountDataEn =
{
  auth: {
    account: 'Account',
    entrance: 'Sign In',
    continueWith: 'Or sign in with username or email',
    password: 'Password',
    remember: 'Remember me',
    term: 'I accept the terms of use',
    comeIn: 'Sign In',
    autoComeIn: 'Automatic sign-in',
    forgotPassword: 'Forgot password',
    register: 'Register',
    authFailed: 'An error occurred during authentication',
    registration: 'Registration',
    registrationFailed: 'An error occurred during registration',
    restorePassword: 'Enter your email to reset your password',
    send: 'Send',
    logout: 'Sign Out',
    accessDenied: 'Access to the resource is denied',
    placeholderLogin: 'Enter username/email',
    placeholderPassword: 'Enter password',
    infoLastLogin: 'Not authenticated. Last login: {formattedDate} ({timeAgo} ago)',
    infoSavedSession: 'Session saved. Use automatic sign-in or enter credentials to log in',
    infoNotAuth: 'Not authenticated. Sign in to access protected resources',
  },
  token: {
    // Token expiry messages
    expiredShort: 'Token expired',
    expiredMedium: 'Token expired. Refresh required',
    expiredFull: 'The token has expired. Please sign in again',

    // Formatted messages for valid tokens
    validShort: 'Valid until: {date}',
    validMedium: 'Expires: {date} ({duration})',
    validFull: 'Token valid until {date}. Time left: {duration}. Will expire {relative}.',
  },
  group: {
    groups: 'Groups',
    id: 'ID',
    idDesc: 'Group identifier',
    name: 'Name',
    nameDesc: 'Full group name',
    displayName: 'Display Name',
    displayNameDesc: 'Group display name',
    edit: 'Edit',
    editDesc: 'Edit group',
    save: 'Save',
    saveDesc: 'Save group',
    duplicate: 'Duplicate',
    duplicateDesc: 'Duplicate group',
    delete: 'Delete',
    deleteDesc: 'Delete group',
    cancel: 'Cancel',
    cancelDesc: 'Cancel group changes'
  },
  notification: {
    id: 'ID',
    idDesc: 'Notification identifier',
    topic: 'Subject',
    topicDesc: 'Notification subject',
    sender: 'Sender',
    senderDesc: 'Notification sender',
    importance: 'Priority',
    importanceDesc: 'Notification priority',
    content: 'Content',
    contentDesc: 'Notification content',
    created: 'Date',
    createdDesc: 'Notification date',
    notification: 'Notifications',
    importanceChief: 'High',
    importanceNormal: 'Normal',
    importanceService: 'Service',
    read: 'Mark as Read',
    readCancel: 'Mark as Unread',
    toArchive: 'Archive',
    fromArchive: 'Unarchive'
  },
  permission: {
    permissions: 'Permissions',
    id: 'ID',
    idDesc: 'Permission identifier',
    name: 'Name',
    nameDesc: 'Internal permission name',
    displayName: 'Name',
    displayNameDesc: 'Permission display name'
  },
  position: {
    positions: 'Positions',
    id: 'ID',
    idDesc: 'Position identifier',
    name: 'Name',
    nameDesc: 'Full position name',
    displayName: 'Display Name',
    displayNameDesc: 'Position display name',
    edit: 'Edit',
    editDesc: 'Edit position',
    save: 'Save',
    saveDesc: 'Save position',
    duplicate: 'Duplicate',
    duplicateDesc: 'Duplicate position',
    delete: 'Delete',
    deleteDesc: 'Delete position',
    cancel: 'Cancel',
    cancelDesc: 'Cancel position changes'
  },
  profile: {
    profile: 'Profile'
  },
  role: {
    roles: 'Roles',
    id: 'ID',
    idDesc: 'Role identifier',
    name: 'Name',
    nameDesc: 'Internal role name',
    displayName: 'Name',
    displayNameDesc: 'Role display name',
    permissionIds: 'Permissions',
    permissionIdsDesc: 'List of permissions for this role'
  },
  settings: {
    settings: 'Settings',
    theme: 'Theme',
    themeLight: 'Light theme',
    themeDark: 'Dark theme',
    viewParams: 'View Parameters',
    showHeader: 'Show header',
    showFooter: 'Show footer'
  },
  user: {
    users: 'Users',
    fio: 'Full Name',
    name: 'First Name',
    surname: 'Last Name',
    fathersName: 'Middle Name',
    birthday: 'Date of Birth',
    snils: 'SNILS Number',
    phoneNumber: 'Phone Number',
    roleName: 'Role',
    profileNames: 'Profiles',
    organizationName: 'Organization',
  },
  account:
  {
    profile: 'Personal Data',
    settings: 'Settings',
    security: 'Security'
  }
};